import { ImageResponse } from "next/og";

/* Favicon: "JJ." in the site's palette, generated by Next at build time. */

export const size = { width: 64, height: 64 };
export const contentType = "image/png";

export default function Icon() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          background: "#faf7f0",
          color: "#2f2c26",
          fontSize: 38,
          fontWeight: 700,
          borderRadius: 12,
        }}
      >
        JJ
        <span style={{ color: "#4c7a55" }}>.</span>
      </div>
    ),
    size,
  );
}
